name: "04 - Pipeline build, test y deploy"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # ETAPA 1: Construir el paquete
  build:
    name: Construir paquete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simular Construccion
        run: |
          echo "Iniciando construccion del paquete..."
          mkdir dist
          echo "Version 1.0" > dist/paquete.txt
          echo "¡Paquete construido con exito!"
      - name: Guardar paquete como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: paquete-distribucion
          path: dist/

  # ETAPA 2: Ejecutar pruebas
  test:
    name: Ejecutar pruebas
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar todas las pruebas
        run: |
          echo "Ejecutando pruebas unitarias..."
          echo "¡Todas las pruebas pasaron exitosamente (100%)!"

  # ETAPA 3: Desplegar
  deploy:
    name: Desplegar aplicacion
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: paquete-distribucion
          path: dist/
      - name: Simular despliegue
        run: |
          echo '------------------------------------------------------------'
          echo 'Desplegando version: ${{ github.sha }}'
          echo 'Rama: ${{ github.ref_name }}'
          echo 'Activado por: ${{ github.actor }}'
          ls -la dist/
          echo 'Despliegue completado exitosamente.'
          echo '============================================================'
