name: 01 - hello worid

# Este workflow se activa de dos formas:
on:
 push:
    branches: [ main ]     #Automáticamnte al hacer push a main
workflow_dispatch:         # Manualmente desde la pestaña Actions de GitHub

jobs:
  hello:
     runs-on:  ubuntu-latest  # Se ejecuta en una máquina virtual Linux

     steps:
        # Paso 1: Obtener el código del repositorio
        - name:  Clonar repositorio
          uses:  actions/checkout@v4

        # Paso 2: Imprimir un saludo simple
        - name:   Imprimir saludo
          run:   echo ' Hola desde Git Hub Actions'
         
       # Paso 3:  Mostrar  información del entorno
        - name:   Información del runner
          run:    |
           echo  '===Información del sistema ==='
           echo  'Sistema operativo:'  $(uname -a)
           echo  'Usuario actual:' $(whoami)
           echo  'Fecha y hora:' $(date)
           echo  'Directorio de T¿trabajo:' $(pwd)

       # Paso 4: Mostrar variables de contexto de Git Hub
        -name:  Variables de GitHub
         run:  |
           echo  'Repositorio: ${{ github.repositoriy }}'
           echo  'usuario que activó el workflow:  ${{ github.actor }}'
           echo  'Rama: ${{ github.ref_name }}'
           echo  'SHA del comit: ${{ github.sha }}'
           echo  'Evento que disparó el workflow: ${{ github.event_name }}'












         
