name: Hello World

on:
  push:
   name: "Hello World"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Imprimir saludo
        run: echo "Hola desde GitHub Actions"

      - name: Informacion del runner
        run: |
          echo "---Informacion del sistema---"
          echo "Sistema operativo: $(uname -a)"

      - name: Variables de GitHub
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Usuario que activo el workflow: ${{ github.actor }}"

      # ESTE ES EL PASO QUE FALTA PARA TU CAPTURA 3 (Paso 6 de la guía)
      - name: Verificar que el Secret esta configurado
        env:
          MI_PASSWORD: ${{ secrets.API_KEY }}
        run: |
          if [ -n "$MI_PASSWORD" ]; then
            echo "El Secret 'API_KEY' fue detectado correctamente de forma segura por el pipeline."
          else
            echo "Error: No se encontro el Secret 'API_KEY'."
            exit 1
          fi
